model = "gpt-5.5"
model_reasoning_effort = "xhigh"

notify = ["/Users/yamazaki/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/home/okayasu/prog/mms.local"]
trust_level = "trusted"

[projects."/home/okayasu/prog/dotfile-work"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[hooks.state]

[hooks.state."/Users/yamazaki/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:4478b87bb9e84a35d0288b542ffa505dd6717d9f1470814cb1d74bfb4afbfced"

[hooks.state."/Users/yamazaki/.codex/hooks.json:post_tool_use:1:0"]
trusted_hash = "sha256:f4e82ba43dc16de418955a973428159254c5137475d65fa5985c222ca497d475"

[hooks.state."/Users/yamazaki/.codex/hooks.json:pre_compact:0:0"]
trusted_hash = "sha256:afcf998ffa61741976c93d1c09831cd69d6ca39267211478b66a8eb51362872e"

[hooks.state."/Users/yamazaki/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:e865201dfc430017473abc69a1b57b3fb637bb1f2dfe5d4f1fdbbffeaf5031a9"

[hooks.state."/Users/yamazaki/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:aed27c2ca63acfacd99bece5e58dcb3fe51dfb15acffd6e4398f49bb0194fc3c"

[hooks.state."/Users/yamazaki/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:df596c7e139c18b47a7c7f5117f4f7508e2e662e0ef26a329bc5e4da4c17023e"

[hooks.state."/Users/yamazaki/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:33b22da3ad1094fccd39f19c8b429c34cec149ebd68150438e2c88d3767176f0"

[hooks.state."/home/okayasu/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:4478b87bb9e84a35d0288b542ffa505dd6717d9f1470814cb1d74bfb4afbfced"

[hooks.state."/home/okayasu/.codex/hooks.json:pre_compact:0:0"]
trusted_hash = "sha256:afcf998ffa61741976c93d1c09831cd69d6ca39267211478b66a8eb51362872e"

[hooks.state."/home/okayasu/.codex/hooks.json:pre_tool_use:0:0"]
enabled = true
trusted_hash = "sha256:e865201dfc430017473abc69a1b57b3fb637bb1f2dfe5d4f1fdbbffeaf5031a9"

[hooks.state."/home/okayasu/.codex/hooks.json:session_start:0:0"]
enabled = true
trusted_hash = "sha256:aed27c2ca63acfacd99bece5e58dcb3fe51dfb15acffd6e4398f49bb0194fc3c"

[hooks.state."/home/okayasu/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:33b22da3ad1094fccd39f19c8b429c34cec149ebd68150438e2c88d3767176f0"

[hooks.state."dotfile-work-codex@dotfile-work-personal:hooks/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:ad71e5ff87a2c17d367f6896b37ca3ccfe108fed57e182180661f9967c792530"

[hooks.state."dotfile-work-codex@dotfile-work-personal:hooks/hooks.json:session_start:0:0"]
trusted_hash = "sha256:0cf931fdd56d33674301160af986b57d5610a5a1060436fbb5ad5760e68f74db"

[hooks.state."dotfile-work-codex@dotfile-work-personal:hooks/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:580f9765ee69111014941295fbc0ccf899c57182ce0c45f2704e1d3ead9ab02f"

[features]
terminal_resize_reflow = true
memories = true
goals = true
prevent_idle_sleep = true
external_migration = true
js_repl = false

[plugins."github@openai-curated"]
enabled = true

[plugins."dotfile-work-codex@dotfile-work-personal"]
enabled = true

[plugins."dotfile-work-codex-extra@dotfile-work-personal"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-05-31T12:22:10Z"
source_type = "local"
source = "/Users/yamazaki/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-31T13:13:56Z"
source_type = "local"
source = "/Users/yamazaki/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[desktop]
ambient-suggestions-enabled = true
appearanceLightCodeThemeId = "github"
appearanceDarkCodeThemeId = "ayu"
codeFontSize = 14
usePointerCursors = true
dictationDictionary = []
composerEnterBehavior = "cmdIfMultiline"
git-pull-request-merge-method = "merge"
git-show-sidebar-pr-icons = true
conversationDetailMode = "STEPS_COMMANDS"

[desktop.appearanceLightChromeTheme]
accent = "#0969da"
contrast = 45
ink = "#1f2328"
opaqueWindows = false
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#1a7f37"
diffRemoved = "#cf222e"
skill = "#8250df"

[desktop.appearanceDarkChromeTheme]
accent = "#e6b450"
contrast = 74
ink = "#bfbdb6"
opaqueWindows = false
surface = "#0b0e14"

[desktop.appearanceDarkChromeTheme.fonts]

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#7fd962"
diffRemoved = "#ea6c73"
skill = "#cda1fa"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/yamazaki/.codex"
CODEX_HOME = "/Users/yamazaki/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "0b0d41e7a14a4903d2f95b0b3f427ed796b12c8edca2fa392a03df43997075ae"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"
